services:
  database:
    image: postgres:17.6
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - data:/var/lib/postgresql/data
  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      restart: always
      env_file:
        - .env
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        SCRIPT_NAME: /pgadmin
      ports:
        - "${PGADMIN_PORT}:80"


volumes:
  data:

