services:
  database:
    image: postgres:17.6
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ongfenixdb
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      SCRIPT_NAME: /pgadmin
    ports:
      - "${PGADMIN_PORT}:80"

volumes:
  data:
