services:
  database:
    image: postgres:17.6
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ongfenix
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - .:/backups
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      SCRIPT_NAME: /pgadmin
    ports:
      - "5050:80"

volumes:
  data:
